---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: data_bags
  encrypted_data_bag_secret_key_path: .chef/encrypted_data_bag_secret
  environments_path: environments
  client_rb:
    environment: production

platforms:
  - name: ubuntu-14.04

common_attrs: &common_attrs
  authorization:
    sudo:
      users:
        - vagrant

development_env: &development_env
  client_rb:
    environment: development

suites:
  - name: base
    run_list:
      - role[base]
    attributes:
      <<: *common_attrs

  - name: base_development
    run_list:
      - role[base]
    provisioner:
      <<: *development_env
    attributes:
      <<: *common_attrs
